### PR TITLE
Implement OIDC templating

### PR DESCRIPTION
**Pull request by tfussell**
For https://github.com/giantswarm/giantswarm/issues/8640

I discovered a bug due to missing error handling and ultimately from a missing template variable (`CloudProvider`). This was truncating the api-server yaml.

Other than that, this PR simply copies OIDC settings from the ignition spec to the api-server yaml if enabled.

### CODE REVIEW

**Comment by stone-z** [comment]
I also just ran into the CloudProvider bug. Is this ready to go in?

**Comment by tfussell** [comment]
> I also just ran into the CloudProvider bug. Is this ready to go in?

I got a little bogged down in `apiextensions` and never quite finished this. Now that the ignition CR/CRD is merged, this PR just needs these other two OIDC flags that I added to the CR after this PR: https://github.com/giantswarm/apiextensions/blob/master/pkg/apis/core/v1alpha1/ignition_types.go#L280-L301

**Comment by tfussell** [comment]
Specifically, `--oidc-groups-prefix` should be set to `GroupsPrefix` and `--oidc-username-prefix` should be set to `UsernamePrefix`. Feel free to fix the conflicts and add these two missing flags or I'll try to do it later today.

**Comment by tfussell** [comment]
Went ahead and fixed this so it should be ready to merge if someone could review. Feel free to merge in the morning too if this is blocking you.

**Review by MarcelMue — APPROVED** [review]
Change LGTM

**Comment by QuentinBisson** [comment]
You are on fire @tfussell Nice

**Pull request merged**
