### PR TITLE
Use go modules

### PR DESCRIPTION
**Pull request by MarcelMue**
I very much don't know what I am doing - but I am trying.

Build succeeded locally.

Towards https://github.com/giantswarm/giantswarm/issues/8639

### CODE REVIEW

**Review by stone-z — APPROVED** [review]
Nice nice nice let's mod these operators

**Comment by stone-z** [comment]
Might need to tag releases to import this in the future until everything is modules but this brand new operator would be the place to do it

**Comment by MarcelMue** [comment]
> Might need to tag releases to import this in the future until everything is modules but this brand new operator would be the place to do it

I am not sure I understand you correctly. Is there anything I should do right now, or do you mean we tag more repos over time?

**Comment by stone-z** [comment]
Nothing to do now. Should add version tag to this repo if it needs to be imported by a dep project

**Comment by MarcelMue** [comment]
Ahh okay - got it. We have a best practice to not import operators into other projects - so this should be fine for now :)

**Pull request merged**
